name: Node.js CI

name: Node.js CI

# Este workflow se ejecuta cada vez que haces push o pull request a main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Usar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test

      - name: Simular proceso de build
        run: |
          mkdir -p build
          echo "Build generado correctamente" > build/build-info.txt

      - name: Guardar artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/
